# Generated by Django 4.1.4 on 2023-01-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Video Başlığı')),
                ('text', models.TextField(verbose_name='Video Konusu')),
                ('image', models.FileField(upload_to='', verbose_name='Video')),
            ],
        ),
        migrations.AlterField(
            model_name='profil',
            name='boy',
            field=models.BooleanField(default=False, verbose_name='Çocuk'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='pinon',
            field=models.BooleanField(default=False, verbose_name='Pin Kodu Aktif'),
        ),
    ]
